### ISSUE TITLE
BD Testing v1.0

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-tests#17]
We need to get this stuff organized so we don't loose focus. This issue tracks all the important changes that need to happen so we can call it a _proper testing_.

Needed:
* [x] Clean unnecessary files of the DataBase folder (Solved with 191601f)
* [x] Employ a modular strategy - #14 (Solved with 76b2605)
* [x] ~~Define the order, how we should test some procedures and their requirements - #15~~

Possible:
* [ ] Track new commits from the latest available .sql and test them out - #16

Future:

* Table creation - needs the new db version before opening a new issue.
* Procedure testing - if new procedures come up in the new db version open a new issue.

**Comment by asantos3** [comment]
I consider the initial version launched with https://github.com/iptomar/projectary-tests/pull/45 - it's a good enough start and it should be iterated on now.
